name: test_project1
version: '1.0'

profile: default

model-paths: ["models"]
seed-paths: ["seeds"]
models:
  test_project1:
      bronze:
        materialized: view
      silver:
        materialized: view
      gold:
        materialized: table

