version: 2
sources: 
  - name: raw
    database: TRAINING
    schema:  public
    tables: 
      - name: customer
        description: "This table has customers which is getting from snowflake"
  